modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "ten4"
version = "26.1.0"
displayName = "Technical Engineering 4"
displayURL = "https://github.com/licphel/technical-engineering-4-1.21.1"
authors = "Licphel"
description = '''A Minecraft tech-mod, featuring logistics and convenient device'''
