modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "ten4"
version = "26.1.1"
displayName = "Technical Engineering 4"
displayURL = "https://modrinth.com/mod/technical-engineering-4"
authors = "Licphel"
description = '''A Minecraft tech-mod, featuring logistics and convenient device, highly configurable.'''
